#!/usr/bin/env python
"""
Script to create the config.py file with the appropriate backend URL.
Run this script to create or update your config file.
"""

import os
import sys
from config import backend_url
def create_config():
    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'config.py')
    
    if os.path.exists(config_path):
        overwrite = input(f"Config file already exists at {config_path}. Overwrite? (y/n): ")
        if overwrite.lower() != 'y':
            print("Operation cancelled.")
            return False
    
    backend_url = input(f"Enter the backend URL [default: {backend_url}]: ") or backend_url
    
    # Write the config file
    with open(config_path, 'w') as f:
        f.write(f"""# Backend configuration
# This file was automatically generated by create_config.py

# URL of the backend server
backend_url = "{backend_url}"
""")
    
    print(f"✅ Config file created at {config_path}")
    print(f"   Backend URL: {backend_url}")
    return True

if __name__ == "__main__":
    success = create_config()
    if success:
        sys.exit(0)
    else:
        sys.exit(1) 