services:
  - type: web
    name: teamshark
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./render_start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DJANGO_SETTINGS_MODULE
        value: fileupload.settings
      - key: HF_TOKEN
        sync: false
    disk:
      name: app-data
      mountPath: /opt/render/app-data
      sizeGB: 2
    autoDeploy: false