# Generated by Django 5.1.7 on 2025-03-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
