# Generated by Django 5.0.2 on 2025-03-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
