# Generated by Django 5.0.2 on 2025-04-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadedfile_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='forecast_days',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
