# Generated by Django 5.0.2 on 2025-04-04 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_uploadedfile_forecast_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)]),
        ),
    ]
