# Generated by Django 5.2 on 2025-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_farmer_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
